language: python
python:
  - 2.7
  - 3.4
  - 3.5
# command to run tests
before_install:
  - pip install --upgrade pip setuptools wheel
install:
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -r requirements.txt
  - pip install codecov
script: 
  - python -m unittest discover -s tests/
  - coverage run --source=kursl -m unittest discover -s tests
after_success:
  - codecov
